services:
  postgres:
    container_name: postgres_orders
    image: postgres:16.4
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      PGDATA: /data/postgres
    volumes: 
      - ./postgres-data:/data/postgres
    ports:
      - "5432:5432"
